<script setup lang="ts">
  import { ref } from 'vue';
  import GridTable from '~/components/GridTable.vue';
  import { Column } from '~/components/grid';

  const columns = ref<Column[]>([
    {
      name: 'Field',
      label: 'Field',
    },
    {
      name: 'Type',
      label: 'Type',
    },
    {
      name: 'Collation',
      label: 'Collation',
    },
    {
      name: 'Null',
      label: 'Null',
    },
    {
      name: 'Key',
      label: 'Key',
    },
    {
      name: 'Default',
      label: 'Default',
    },
    {
      name: 'Extra',
      label: 'Extra',
    },
    {
      name: 'Privileges',
      label: 'Privileges',
    },
    {
      name: 'Comment',
      label: 'Comment',
    },
  ]);

  const datas = ref([
    {
      Field: 'TABLE_CATALOG',
      Type: 'varchar(512)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'TABLE_SCHEMA',
      Type: 'varchar(64)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'TABLE_NAME',
      Type: 'varchar(64)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLUMN_NAME',
      Type: 'varchar(64)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'ORDINAL_POSITION',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'NO',
      Key: '',
      Default: '0',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLUMN_DEFAULT',
      Type: 'longtext',
      Collation: 'utf8_general_ci',
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'IS_NULLABLE',
      Type: 'varchar(3)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'DATA_TYPE',
      Type: 'varchar(64)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'CHARACTER_MAXIMUM_LENGTH',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'CHARACTER_OCTET_LENGTH',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'NUMERIC_PRECISION',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'NUMERIC_SCALE',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'DATETIME_PRECISION',
      Type: 'bigint(21) unsigned',
      Collation: null,
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'CHARACTER_SET_NAME',
      Type: 'varchar(32)',
      Collation: 'utf8_general_ci',
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLLATION_NAME',
      Type: 'varchar(32)',
      Collation: 'utf8_general_ci',
      Null: 'YES',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLUMN_TYPE',
      Type: 'longtext',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLUMN_KEY',
      Type: 'varchar(3)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'EXTRA',
      Type: 'varchar(30)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'PRIVILEGES',
      Type: 'varchar(80)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'COLUMN_COMMENT',
      Type: 'varchar(1024)',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: '',
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
    {
      Field: 'GENERATION_EXPRESSION',
      Type: 'longtext',
      Collation: 'utf8_general_ci',
      Null: 'NO',
      Key: '',
      Default: null,
      Extra: '',
      Privileges: 'select',
      Comment: '',
    },
  ]);
</script>

<template>
  <GridTable :columns="columns" :rows="datas" />
</template>

<style scoped></style>
